name: CI

on:
  workflow_dispatch:
    inputs:
      abc:
        type: boolean
        description: True or False

jobs:
  build-on-dev:
    if: ${{ inputs.abc }}
    uses: ./.github/workflows/dependent-action.yml
      
