name: CI

on:
  workflow_dispatch:
    inputs:
      abc:
        type: boolean
        description: True or False

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.abc }} / ${{ inputs.abc }}"
